import "./globals.css";
// Next
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Open_Sans, Noto_Sans } from "next/font/google";
// Clerk
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
// Components
const ThemeProvider = dynamic(
  () => import("@/components/providers/ThemeProvider")
);

const font = Noto_Sans({
  subsets: ["latin", "latin-ext"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Webranch Talk",
  description: "Generated by hejzbh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body
          className={`${font.className}`}
          style={{
            background:
              "radial-gradient(circle, rgba(18,18,22,1) 0%, rgba(21,21,25,1) 35%, rgba(18,18,22,1) 100%)",
          }}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {" "}
            <main className="text-white">{children}</main>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
